### ISSUE TITLE
day2night datasets

### ISSUE THREAD

**Issue by kidach1** [xinntao/DNI#2]
Thank you for sharing your awesome work.
I was very impressed by vividness of day to night example. According to Sec 4.2 of your paper, the translation algorithm base on CycleGAN or Pix2Pix, right? Could you tell me which datasets did you use?

**Comment by xinntao** [comment]
We used CycleGAN for the day2night application. 
We crawled day and night images from the Internet.

**Comment by kidach1** [comment]
Thanks!
